<a href="https://colab.research.google.com/github/Arthur6363/Deep-Learning-ML/blob/main/Wine_PCA_LDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("winequality_white.csv")

In [2]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [3]:
x = df.drop("quality", axis=1)
y = df["quality"]

In [8]:
df["quality"].unique()

array([6, 5, 7, 8, 4, 3, 9])

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20, random_state=63)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

PCA

In [16]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2 )
x_train2 = pca.fit_transform(x_train)
x_test2 = pca.transform(x_test)

In [20]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(x_train , y_train)

LogisticRegression(random_state=0)

In [23]:
model2 = LogisticRegression(random_state = 0)
model2.fit(x_train2 , y_train)

LogisticRegression(random_state=0)

In [24]:
y_pred = model.predict(x_test)
y_pred2 = model2.predict(x_test2)

In [29]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[  0   0   1   4   0   0]
 [  0   2  18  10   0   0]
 [  0   0 160 138   3   0]
 [  0   1  68 344  22   0]
 [  0   0  12 125  33   0]
 [  0   0   4  25  10   0]]


In [35]:
cm2 = confusion_matrix(y_test, y_pred2)
print(cm)

[[  0   0   1   4   0   0]
 [  0   2  18  10   0   0]
 [  0   0 160 138   3   0]
 [  0   1  68 344  22   0]
 [  0   0  12 125  33   0]
 [  0   0   4  25  10   0]]


In [33]:
cm3 = confusion_matrix(y_pred, y_pred2)
print(cm)

[[  0   0   1   4   0   0]
 [  0   2  18  10   0   0]
 [  0   0 160 138   3   0]
 [  0   1  68 344  22   0]
 [  0   0  12 125  33   0]
 [  0   0   4  25  10   0]]


In [38]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components=2)
x_train_lda = lda.fit_transform(x_train,y_train)
x_test_lda = lda.transform(x_test)

In [39]:
model_lda = LogisticRegression(random_state = 0)
model_lda.fit(x_train_lda , y_train)
y_pred_lda = model_lda.predict(x_test_lda)

In [43]:
model_lda.score(x_test_lda, y_test)

0.539795918367347

In [40]:
cm4 = confusion_matrix(y_pred, y_pred_lda)
print(cm4)

[[  2   1   0   0]
 [  1 225  37   0]
 [  0  23 603  20]
 [  0   0  14  54]]
